import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEmail, IsOptional, IsString, Length, Matches } from 'class-validator';

export class InitialSetupDto {
  @ApiProperty({ example: 'Λογιστικό Γραφείο Παπαδόπουλος' })
  @IsString()
  @Length(2, 160)
  officeName!: string;

  @ApiPropertyOptional({ example: '123456789' })
  @IsOptional()
  @IsString()
  @Matches(/^\d{9}$/)
  officeVatNumber?: string;

  @ApiPropertyOptional({ example: 'info@logistirio.gr' })
  @IsOptional()
  @IsEmail()
  @Length(3, 160)
  officeEmail?: string;

  @ApiPropertyOptional({ example: '2101234567' })
  @IsOptional()
  @IsString()
  @Length(3, 40)
  officePhone?: string;

  @ApiPropertyOptional({ example: 'Σταδίου 1, Αθήνα' })
  @IsOptional()
  @IsString()
  @Length(3, 255)
  officeAddress?: string;

  @ApiProperty({ example: 'Μαρία Παπαδοπούλου' })
  @IsString()
  @Length(2, 160)
  adminFullName!: string;

  @ApiProperty({ example: 'maria@logistirio.gr' })
  @IsEmail()
  @Length(3, 160)
  adminEmail!: string;

  @ApiProperty({ minLength: 14 })
  @IsString()
  @Length(14, 120)
  adminPassword!: string;

  @ApiProperty({ description: 'One-time secret generated by the local Windows installer.' })
  @IsString()
  @Length(32, 256)
  setupToken!: string;
}
