ALTER TABLE `PayrollContract`
  ADD COLUMN `workWeekdays` VARCHAR(20) NOT NULL DEFAULT '1,2,3,4,5',
  ADD COLUMN `dailyStartTime` VARCHAR(5) NOT NULL DEFAULT '09:00',
  ADD COLUMN `dailyEndTime` VARCHAR(5) NOT NULL DEFAULT '17:00',
  ADD COLUMN `breakMinutes` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `breakWithinWorkingTime` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `digitalCardEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `flexibleArrivalMinutes` INTEGER NOT NULL DEFAULT 0;

ALTER TABLE `PayrollErganiDeclaration`
  MODIFY COLUMN `type` ENUM(
    'HIRING',
    'INITIAL_WORK_SCHEDULE',
    'WORK_SCHEDULE_CHANGE',
    'DIGITAL_CARD_ENROLLMENT',
    'EXECUTIVE_STATUS_ACQUIRED',
    'EXECUTIVE_STATUS_LOST',
    'PAY_CHANGE_AGREEMENT',
    'PAY_CHANGE_LEGISLATION',
    'SPECIALTY_CHANGE',
    'WORKPLACE_CHANGE',
    'PART_TIME_TO_FULL_TIME',
    'FULL_TIME_TO_PART_TIME',
    'FULL_TIME_TO_ROTATING',
    'FULL_TIME_TO_ROTATING_UNILATERAL',
    'FIXED_TO_OPEN_ENDED',
    'FIXED_TERM_EXTENSION',
    'WORK_TIME_ARRANGEMENT',
    'OTHER'
  ) NOT NULL;
