ALTER TABLE `Document`
  MODIFY `documentType`
    ENUM('SALES_INVOICE', 'PURCHASE_INVOICE', 'CREDIT_NOTE', 'PURCHASE_CREDIT_NOTE', 'RETAIL_RECEIPT')
    NOT NULL;

ALTER TABLE `DocumentPostingRule`
  MODIFY `documentType`
    ENUM('SALES_INVOICE', 'PURCHASE_INVOICE', 'CREDIT_NOTE', 'PURCHASE_CREDIT_NOTE', 'RETAIL_RECEIPT')
    NULL;
