export type UserRole =
  'SUPER_ADMIN' | 'ACCOUNTING_OFFICE_ADMIN' | 'ACCOUNTANT' | 'ASSISTANT' | 'CLIENT_READONLY';

export const ACCOUNTING_CONTROL_ROLES: UserRole[] = [
  'SUPER_ADMIN',
  'ACCOUNTING_OFFICE_ADMIN',
  'ACCOUNTANT',
];

export const ADMIN_ROLES: UserRole[] = ['SUPER_ADMIN', 'ACCOUNTING_OFFICE_ADMIN'];
