ALTER TABLE `ClientCompany`
  ADD COLUMN `entityType` ENUM('COMPANY', 'FREELANCER', 'SOLE_PROPRIETOR', 'NON_PROFIT', 'OTHER') NOT NULL DEFAULT 'COMPANY',
  ADD COLUMN `professionLabel` VARCHAR(191) NULL,
  ADD COLUMN `myDataMode` ENUM('ACCOUNTING_OFFICE_AUTHORIZED', 'OWN_API_CREDENTIALS_ENV_REF', 'MANUAL_UPLOAD', 'NOT_CONFIGURED') NOT NULL DEFAULT 'ACCOUNTING_OFFICE_AUTHORIZED',
  ADD COLUMN `myDataAuthorized` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `myDataCredentialRef` VARCHAR(191) NULL;
